### ISSUE TITLE
The Sun disappears but process ginj still active

### ISSUE THREAD

**Issue by Creamers158** [Ginj-capture/Ginj#13]
I've started the Ginj with  'ginj.exe /create-i4j-log' to capture a potential error when the yellow sun disappears.
I've been able to reprodure it (sometimes )-: but cannot seem to find an error in the log.

It mostly happens when having a capture open with a image from the history box but not always.
I would like a suggestion how to troubleshoot this better and give more details/errors.

Is the 'ginj.exe /create-i4j-log' the only way or are there more verbose options. If the process keeps running but the sun disappears, will it be logged?

Thx!  

Ps, could the 5sec timer at auto-hide be adjustable or shorter ?

**Comment by vicnevicne** [comment]
Thanks for your report. I've never seen the sun disappear so I'd be glad to understand. 
In fact, maybe the sun is still there but painted off-screen, in which case there will be no log. In that case, changing resolution (or just toggling the Task Bar "auto hide) setting) should bring the Sun back in a visible area.
Regarding the logs, assuming you have OpenJDK 14 installed, could you open a command prompt in Ginj's install folder and type `java -jar Ginj.jar` and see if the issue can be reproduced. 
If so, you should get details in the console if an exception occurs.
If not, that may be a problem with the launcher which is part of the installer (but I doubt it).

Oh, as for the 5sec timer, it's already down to 3 seconds in v0.3.5 released yesterday :-) but I could make it a param indeed.

**Comment by infinitebizmedia** [comment]
> I've started the Ginj with 'ginj.exe /create-i4j-log' to capture a potential error when the yellow sun disappears.
> I've been able to reprodure it (sometimes )-: but cannot seem to find an error in the log.
> 
> It mostly happens when having a capture open with a image from the history box but not always.
> I would like a suggestion how to troubleshoot this better and give more details/errors.
> 
> Is the 'ginj.exe /create-i4j-log' the only way or are there more verbose options. If the process keeps running but the sun disappears, will it be logged?
> 
> Thx!
> 
> Ps, could the 5sec timer at auto-hide be adjustable or shorter ?

I got the same behavior but only after i upgraded from 3.2 to 3.5. I actually needed to re-install 3.5 to get it to work.

**Comment by vicnevicne** [comment]
@infinitebizmedia it could be due to the fact that in 0.3.2 the sun position was remembered in "single-display" coordinates, while in more recent versions the coordinates are "across displays", so there are areas with valid coordinates that are actually off screen. Do you have a multi-display setup ?
@Creamers158 Same question: Do you have a multi-display setup ? Thanks.

**Comment by raultakahashi** [comment]
I've experienced this multiple times as well and haven't been able to pinpoint pattern of cause.  I have a 3-monitor setup, if that helps any.

**Comment by Creamers158** [comment]
I have it also multiple times, just now ago also. I use also a 3-monitor setup. (laptop-monitor-monitor)
I tried to adjust resolution and cloning to get the sun back, but dont seem to be able. I need to kill the process and start again.

**Comment by vicnevicne** [comment]
Strange that I cannot reproduce it... So I would need your help a bit more...
- Can you confirm it happens "all of a sudden" and is not linked to any particular action ?
- Next time it happens, can you toggle the Windows taskbar "auto-hide" setting ? Setting it ON then OFF (or reverse) has the side-effect of moving all windows inside the visible area. If the widget reappears, it is a coordinate issue. If not, I have to look somewhere else.
Thanks

**Comment by Creamers158** [comment]
I succeed usually to create snaps and leave them on my screen. I click to create new snaps and keep doing stuff. Like now I succeeded to disappear the sun. Tried what you described:  Taskbar settings - Automatically hide the taskbar in desktop mode ON and OFF.  The sun doesnt appear.
Cant quit produce exact steps to reproduce, it's just suddenly away.

Have a nice holiday!! (Same here for me in NL ;)

**Comment by Creamers158** [comment]
Just now I clicked the sun capture button, nothing more nothing less, for the first this day and it disappeared instantly. Process still running.

**Comment by vicnevicne** [comment]
Very strange that I never got into this. I'm adding debug code to the next version. Hopefully we'll be able to rule out some parts.
Btw, can you try running Ginj without its launcher ?
You can do it by opening a command prompt then typing:
```
C:
cd C:\Program Files\Ginj\jre\bin
java -jar ..\..\Ginj.jar
```
If it does not happen anymore, it's the launcher (but I doubt it)

**Comment by Creamers158** [comment]
Tried to force it, but yet no disappearing sun. Will leave it this way and start it using java -jar.  I'll be on holiday so not using it very much. I'll report back.

**Comment by Creamers158** [comment]
Just wanted to take another snapshot and my Sun was missing. Now, I dont know if this is the same issue and this thread but makes me wonder. (btw, running using java -jar now)
The Sun is hiding behind windows...and not coming to the front.
![thereitis](https://user-images.githubusercontent.com/6506666/88462956-a02b1c80-ceaf-11ea-93c8-a5b137f11631.png)

**Comment by vicnevicne** [comment]
Oh, so it could be that the sun was always there, but just hiding behind ~~clouds~~ opened windows all the time ? That's an interesting observation. But the fact that it does not react to mouse hovering is not good of course.
But how did you "reveal" the sun ? By giving it focus (clicking on it) ? Thanks.

**Comment by Creamers158** [comment]
I didnt see the Sun so I began to look for my cmd prompt where I started Ginj.jar, when minimizing stuff I saw my Sun again.
At first I thought it came back suddenly, but very fast after I noticed that every window maximized or not was covering the Sun.
So the Sun wasn't in front all the time until I used it again by clicking on it to capture a snapshot.
In other words, I couldn't give it focus with a window in front of it, so I had to clear all windows blocking the Sun, click on it, and then I could restore the windows again and it stayed in front again.

**Comment by vicnevicne** [comment]
In version 0.3.6 (just released), I added logging for window moves (new coordinates should be logged on each move) as well as a line when widget window is "disposed" (closed by a normal condition). 
If the "disappearance" really happens again, it should give us an insight.
But if I understand correctly, all this time, it never really "disappeared", it just "simply" lost its "always on top" behaviour? Is that correct ? In that case, the logging will be useless of course.
Maybe (just thinking out loud) you have another app which requests to be "always on top" and Java cannot share its place once another window takes it... I'll have to investigate.
In the meantime, don't hesitate to upgrade anyway ;-)

**Comment by Creamers158** [comment]
Okay, back ;) The Sun is missing again, but now I'm sure it's not behind another window.
Btw, I used the latest version 0.3.6. But looking at the logs there is nothing in there that I can use I guess. (  i4j_log_Ginj_7829257875733270798.log    i4j_nlog_13.log  using ginj.exe /create-i4j-log)
How to troubleshoot this with 0.3.6 and the logging ?

**Comment by vicnevicne** [comment]
3 elements:
- In the logs, you should see lines like
`Widget location = (842, 0).`
These indicate where the widget is placed or moved. It would be interesting to note where the last coordinates are when the widget disappears. Note: (0,0) is the top left corner of the primary display, increasing to the right and down. All others displays are relative to that point (so negative X if the secondary display is positioned to the left of the primary and the widget is on that screen). If it's out of bounds, then it's a window positioning issue.
- In the logs, you should see a line stating
`StarWindow disposed.`
when the widget is closed by "normal" means. If you get that line in the log when the widget disappears, it means something closed the window (even though the launcher is still active).
- Now that capture hotkey is supported, you can configure a hotkey, and if the widget disappears, see if the hotkey still works. If it does, it means the window is still alive, just not displayed.

As very few people reported the issue (and I could not reproduce it myself till now), I'm leaning towards a conflict with another background app. Do you have "special apps" that I could install too, that could be related to Desktop management, always on top widgets, etc ?
Thanks for your help.

**Comment by Creamers158** [comment]
See the logfile, cant find what you explained: https://pastebin.com/6dy3uA94

I use Discord alot and to be honest I thought that could be the problem, but can't say that for sure but I use that on the same main laptop screen where my Sun is, cause I had the feeling that could be the issue.

Will try the hotkey, good idea!

**Comment by Creamers158** [comment]
Just managed to let it disappear again using discord, but dont have a clue why or when it disappears. I just keep clicking snapping etc.

And you where right!!  Using the hotkey shows the Sun again at the same spot same screen. It was there but not visible or usable.

The log from this time but no logging about coordinates.
https://pastebin.com/ACMAEKXs

**Comment by Creamers158** [comment]
Thinking about it, the disappearing happens between clicking on the 'capture' key and the crosshair that doesn't show up.
The Sun disappears when clicking on the 'capture' key, that's normal, but because the crosshair never appears it's stuck in that 'inbetween' state.

**Comment by vicnevicne** [comment]
Hmmm several things to troubleshoot I’m afraid:
- Where does the console log go ? Clearly your log (thanks) is about install4J stuff but does not contain the Java debug messages I’m generating...
- Anyway my added logging wouldn't help as it’s neither a coordinates nor a premature exit issue
- Still no clue what causes the issue
- I might install discord and see if I can reproduce the issue...

One more idea: if you start Ginj using the command prompt by typing
java -jar Ginj.jar
then do you see the traces regarding window location on the console (as well as maybe hotkey registration) ?
If so, can you try to cause a widget disappearance and see if the console gives more info (I’m hoping for a stacktrace) ?

Thanks.

**Comment by Creamers158** [comment]
Tried alot of snaphosts, no disappearing Sun yet using:
```
C:
cd C:\Program Files\Ginj\jre\bin
java -jar ..\..\Ginj.jar
```
![hotkay](https://user-images.githubusercontent.com/6506666/88489982-739eff80-cf98-11ea-9a2a-8d5d3d04bf38.png)

**Comment by vicnevicne** [comment]
Ah-ha... 
So it could be launcher-related in the end... I admit as I'm developing most of the time, I'm testing it without the launcher.
That being said, I already have the answer to the question "Where does the console log go?":
![image](https://user-images.githubusercontent.com/842233/88490806-6422b500-cf9e-11ea-9f80-0d1d8a0afcf4.png)
-> nowhere currently :-)
I'll enable that option in the next release.
 
In the meantime, do you see an "error.log" file next to Ginj.exe ? If the last launcher session caused an error, its trace should be in there...

**Comment by Creamers158** [comment]
![no](https://user-images.githubusercontent.com/6506666/88515878-aa9f0080-cfec-11ea-9908-cb4834f0a066.png)

**Comment by vicnevicne** [comment]
(Oops didn't mean to close the issue)
No error.log seems to indicate there are no caught exceptions...
I've [added some code](https://github.com/Ginj-capture/Ginj/blob/bb61fa193705b2f52b7580787d7c827ae84d4b58/src/main/java/info/ginj/ui/StarWindow.java#L128) to try to get back on top if the window state gets modified. Let's see in the next version if it improve things... Plus, it should have an output.log for non-error logging.

**Comment by vicnevicne** [comment]
Can you please test v0.3.7 and tell me if it's better ?

**Comment by raultakahashi** [comment]
I'm not tech savvy at all so just coming in to comment this is still happening numerous times a day.  I usually quit app from the small icon taskbar or force close it and open the app again to fix and get the sun back.

For the record, I'm using 3 monitors (2 plugged into dock, 1 direct to laptop).

**Comment by Creamers158** [comment]
@raultakahashi  could you check when it happens again if it is hidden behind a window. I'm lately not using the multi monitor setup so I havent had the issue. (Same setup as you have).
Today I noticed that my Sun was also missing, but hidden behind a maximized window. Didn't bother to do anything but later it was visible again.

**Comment by raultakahashi** [comment]
@Creamers158 Sure, I'll check.  But I can tell you the reason why I even notice it gone is because my hotkey stops working.

**Comment by raultakahashi** [comment]
@Creamers158 Just happened again and no sun anywhere to be found after closing each window one by one.  Again only found it was gone because my hotkey wasn't working.  :)

**Comment by vicnevicne** [comment]
Hi. Thanks for the details.
It's really a weird problem because and I'm wondering if we're not having different bugs that all look like "the sun is gone" but are due to different causes. What we gathered so far (correct me if I'm wrong):
- It doesn't happen on all PCs (I *never* got it
- It mostly (or only) happens in multi-monitor setups
- Sometimes, it's just hidden behind maximized windows but the hotkey still works (tbc ?)
- Sometimes it's nowhere to be found, and even the hotkey doesn't respond
- In all cases, the tray icon is always there and responds (aka it's not just crashed)
Is that correct ? 
I'm afraid the case where it's hidden behind other windows but all the rest behaves as expected might be impossible to solve because we depend on Java's own ability to gain "top level" and the javadoc for [toFront()](https://docs.oracle.com/javase/7/docs/api/java/awt/Window.html#toFront()) states "Every attempt will be made to move this Window as high as possible in the stacking order; however, developers should not assume that this method will move this Window above all other windows in every situation." ...
On the other hand, the case where it disappears and no shortcut works anymore is more worrying, It's like if the window had been disposed. 
I intend to improve logging (in particular for this case but also in general), but as you might have guessed from the slower release pace, pressure at work is quite high these days...

**Comment by raultakahashi** [comment]
Just my personal anecdote on: 

"In all cases, the tray icon is always there and responds (aka it's not just crashed)
Is that correct ?"  

This is correct to an extent.  When the sun is gone and hotkey stops working, the tray icon remains.  However, the "Capture" in tray icon does not work.  All other menu actions (History, More, Check for Updates, Exit) DO work. 

Hope that helps!

**Comment by Creamers158** [comment]
I've been working on my lapto lately without the extra monitors and just now I had the same exact problem. Sun disappering, trayicon active but no capture possible, just like raultakahashi described.

**Comment by Creamers158** [comment]
Since 4 days no problems yet......will keep it running as described.

**Comment by Creamers158** [comment]
Now 8 days later no problems so far...will keep using it and will let you know.

**Comment by raultakahashi** [comment]
I just figured out how to find the custom install path my work PC used and using it console mode now.  Used to crash every 3rd or 4th attempted use and I use it a lot so this equated to 8-10 restarts a day.  Been using it all day today and no crashes!

**Comment by Creamers158** [comment]
Sometimes the Sun hides behind all open windows. When I move them away and take a screenshot the Sun will be on the front again when I maximize the previous windows again. In other words, taking a capture moves the Sun back to the front for all windows.  Havent had any other issues where the Sun is disappearing.

**Comment by vicnevicne** [comment]
Thanks for all the feedback. 
From this (and a friend's experience), I have a growing feeling that starting Ginj with the batch file solves the "Sun disappears" issue or at least makes it much less frequent (although I can't really explain why).
The fact that the widget hides behind other windows may be something we cannot solve as Java's documentation clearly states that it cannot guarantee topmost position every time (see [above](#issuecomment-676415729)).
Let's keep this issue under monitoring, and if improvement is confirmed, I'll try to wrap up a cleaner "batch-file" launcher, and will add a notification inside Ginj when a new version is available.

**Comment by vicnevicne** [comment]
FWIW, I encountered the case on the laptop I'm using at work, and could even reproduce it and trace it down to an Out Of Memory exception when performing the capture, which forces an abrupt quit of the capture code and skips the widget re-display part. 
The cause of this exception is not found yet though, and it's strange that it does not happen on all machines. Looks like the capture area returned is infinite or something, and the capture cannot be performed. 
I've added some debug code that will be in the next version to track down the issue.

**Comment by raultakahashi** [comment]
Can concur.  I'm back to crashing every 2nd or 3rd capture.  

Log shows Memory error:
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

Guess I should start by closing one of my 76 Chrome tabs. :)

**Comment by vicnevicne** [comment]
Hmm, the OutOfMemory error means Ginj has eaten all the memory the Java process was given, no matter what other processes live on the machine of how much RAM it has.
What is puzzling is that most PCs have no issue whatsoever, but on some configs, each capture seems to reserve RAM and never give it back.
If I may, could you go to the About dialog and copy/paste the Screen configuration part here ? Also, could you download and install the 0.4.2-pre to see if the logs show decreasing memory like in the log above ?
I'm trying to find what could be similar/different beween PCs exhibiting the issue and others.

**Comment by raultakahashi** [comment]
Here is that info:

Configuration: Screen.config 0.0: 2560x1440@0,0 minus 0/0/30/0 insets.Screen.config 1.0: 1920x1080@2560,0 minus 0/0/30/0 insets.Screen.config 2.0: 1920x1080@-1920,943 minus 0/0/30/0 insets.Screen.config 3.0: 1920x1080@-1924,-137 minus 0/0/30/0 insets.

I'll give 0.4.2 a shot now and report back.

**Comment by vicnevicne** [comment]
Thanks for the info
Hmm the total surface you have is 6400px horizontal (from -1920 to 2560+1920) times 2160 (from -137 to 943+1080), or a 13.8 Mpx bounding box, and now that I think of it, my work PC (that exhibited the OutOfMemoryError) also has much screen real estate, while most of my tests were made on a 1920x1080 or about 2Mpx, so I guess you encounter the OutOfMemory 7 times faster than I do. 
I rechecked the capture code and discovered that I "dispose()" the window each time a capture has been made, but disposing does not seem to make the objects available for garbage collection, so the reserved memory is not freed.
I'll try to change that. Hopefully we're on the right track :-). Thanks again

**Comment by vicnevicne** [comment]
OK. I think it's fixed in [v0.4.2](https://github.com/Ginj-capture/Ginj/releases/tag/v0.4.2) (not in 0.4.2-pre) :-)

Java is known for its memory management with a garbage collector which automatically frees up used memory when nothing points to it anymore, but there are exceptions. The most well known are unclosed connections (DB, network, ...), but JFrames are another case, [as observed here](https://stackoverflow.com/questions/39437481/jframe-is-never-garbage-collected).
A normal app does not create windows all the time and windows don't use up much ram anyway. But the way Ginj worked, a new window was created for each capture and it allocated space for an uncompressed image spanning all displays. When selection was done, these Windows were "dispose()'d" but Java kept a reference to them and all the objects they referenced lived forever.
Now several improvements have been made, mainly consisting in recycling JFrames over and over, and also removing references to created objects when closing them.

So hopefully the disappearing widget (not the "hiding behind other windows") issue is fixed for good, but I'll keep this bug open until it is confirmed.

Feedback welcome !

**Comment by raultakahashi** [comment]
Saw 4.3 was up so I just updated to that one.  Will report on results once I get a day or two of actual use.

**Comment by raultakahashi** [comment]
Sun still crashing and disappearing on 4.3.  Now it's always on second screen capture.  First one works, second one makes the sun disappears and stops working.

Should I try 4.2?

Log:
Sep 22, 2020 2:31:13 PM info.ginj.ui.CaptureSelectionFrame$CaptureMainPane <init>
INFO: Capturing area: java.awt.Rectangle[x=-1924,y=-137,width=6404,height=2160]
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/sun.awt.windows.WRobotPeer.getRGBPixels(WRobotPeer.java:66)
	at java.desktop/java.awt.Robot.createCompatibleImage(Robot.java:501)
	at java.desktop/java.awt.Robot.createScreenCapture(Robot.java:400)
	at info.ginj.ui.CaptureSelectionFrame$CaptureMainPane.<init>(CaptureSelectionFrame.java:157)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:138)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:56)
	at info.ginj.ui.AbstractAllDisplaysFrame.open(AbstractAllDisplaysFrame.java:62)
	at info.ginj.ui.CaptureSelectionFrame.open(CaptureSelectionFrame.java:98)
	at info.ginj.ui.StarWindow.onCapture(StarWindow.java:907)
	at info.ginj.ui.StarWindow.lambda$registerHotKey$6(StarWindow.java:288)
	at info.ginj.ui.StarWindow$$Lambda$114/0x0000000100298040.onHotKey(Unknown Source)
	at com.tulskiy.keymaster.common.Provider$HotKeyEvent.run(Provider.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by vicnevicne** [comment]
Gosh ! How can it be ? I made dozens of captures in a row while monitoring available memory and got a nice "reserve/release" pattern, with no memory leak.
No, I'm afraid 0.4.2 will be no better (and has other issues).

Maybe the Robot class temporary needs more space internally... 
Could I ask you to try this: in the .bat file that launches Ginj, increase the memory made available to the Java process, like so:
```
jre\bin\javaw.exe -Xmx128M -jar Ginj.jar >>%TEMP%\ginj.log 2>&1
```
The number (here 128M) determines how much memory Java can use at a maximum (128 MB). By default, it is 64 MB if I'm not mistaken. In other words, it will allow Ginj to use twice the usual memory. 
With this change...
- If Ginj never hangs, it means the "Robot" class I'm using temporary requires a large amount of memory
- If Ginj hangs after 4 captures, there clearly still is a memory leak
- If Ginj still hangs on the second capture, then I'm puzzled.

Thanks for your help and patience.

**Comment by raultakahashi** [comment]
Eureka! This did the trick.  I've captured 25+ in a row without issue.

So happy =D

Will report back if it ends up crashing again.

**Comment by vicnevicne** [comment]
Oh, that's really great news !
So I guess your screen surface is so big that a capture requires more RAM than the default Java settings allow.
I'm going to change the default settings of the standard launcher.
Note: instead of using the batch file, you can edit the Ginj.vmoptions file (it's a plain text file) and uncomment the "-Xmx512M" line (512MB is clearly too much, feel free to adjust). Once that is done, you can use the Ginj.exe launcher and check that it works too.

**Comment by vicnevicne** [comment]
The RAM increase fix is now included in release 0.4.4.
Will reopen if issue comes back. Note also that Ginj*.log files are now generated in the user folder.

**Comment by vicnevicne** [comment]
Reported again in issue #33

**Comment by vicnevicne** [comment]
I thought the issue was due to a temporary memory consumption and increasing the heap solved the issue, but I now think there is a memory leak somewhere. Seems to occur more frequently with multiple and large displays.
I'll try to dig further but let's hope it is not in the native JDK code... crossing fingers.
In the meantime, can you try increasing the ram as indicated above ?

**Comment by Creamers158** [comment]
To be honest, I've been restarting Ginj also more often but toke it for granted. Let's re-evaluate and troubleshoot this.
What are some good steps to begin with? When the sun disappears collecting the logs again from the user folder?
I restarted the Sun today, looking at the logs one of the last lines shows:
[2021-03-18 15:11:17] [INFO   ] After capture - about 21547720 bytes (20.5 MiB) free. 

I'll collect the logs again when the Sun is disappeared.

One thing, sometimes the Sun is disappeared, but just nog visible. I choose to exit Ginj from the tray icon but then choose No so it doesnt exit on the confirmation window. The Sun will in this case be on top again, but this does not work everytime.

**Comment by gfmoore** [comment]
So, I've been able to reproduce the issue, but it takes a while so this may not be definitive.
I tried just using ginj time after time to grab a screen shot, no problems. I didn't paste the image. I do notice that when you click on the SW capture lug then the sun disappears of course. So at some point the sun is re-instated. Is this where the issue lies? After all the app is still running, just can't do anything with it.
I noted that after trying many times, I then decided to open MS Word (2010) and bang the sun disappeared. Odd. So with Word opened and grabbing/pasting I was able to reproduce the behaviour. I'll do it again in a minute from scratch and count how often I have to do it before it disappears. The Word thing may just be a red herring.

**Comment by gfmoore** [comment]
It happened on the 11th grab (interesting number!!! 10 that is.) I'll try again and see if its the same number of times.

**Comment by Creamers158** [comment]
I've openen Word 2016 and grab / pasted 11 times without problems.
Sometimes when I click on the select button I should get the 'select lines' but they will never appear and the sun is also disappeared.

**Comment by vicnevicne** [comment]
Hi,
There may be cases where the Sun disappears for other reasons (getting hidden behind other windows), but I'd first want to determine whether we're running into memory issues or not, so could I ask you to:
- exit Ginj and restart it using the following command line (to run from a cmd prompt inside the Ginj install folder):
`jre\bin\javaw.exe -Xmx128M -jar Ginj.jar >>%TEMP%\ginj.log 2>&1`
(If you have issues running such a command, don't hesitate to ask.)
- confirm whether the icon disappears or not after several captures
- if so, open the ginj.log file created inside your temp folder and post the last lines to see if they are similar to the OutOfMemoryError exception above
Thanks,
Vicne

**Comment by gfmoore** [comment]
I'll get to it tomorrow, bit busy at moment :)

**Comment by gfmoore** [comment]
Ok just tried doing that and sun disappeared after just 4/5 grab and pastes.

Tried again and same result. On the 5th select the select lines don't appear and sun has disappeared. 

I bet you weren't expecting that. 

Is it something to do with the code that activates the select bars/lines?

**Comment by gfmoore** [comment]
Where's the temp folder?

**Comment by gfmoore** [comment]
I've done a search for ginj.log and it doesn't exist?

**Comment by Creamers158** [comment]
I've had the same where the sun disappeared after a few screenshots (multiple connected screens), but the ginj.log was still empty.

**Comment by Creamers158** [comment]
Started again with above commandline.
Now the Sun dissappeared again and this log was found:
[2021-03-22 10:04:57] [INFO   ] Ffmpeg found, specified in prefs file 
[2021-03-22 10:04:57] [INFO   ] Starting Windows global hotkey provider 
[2021-03-22 10:04:57] [INFO   ] Widget location = (963, 0). 
[2021-03-22 10:04:57] [INFO   ] Registering hotkey: HotKey{ctrl CLOSE_BRACKET} 
[2021-03-22 10:04:57] [INFO   ] Widget location = (963, 0). 
[2021-03-22 10:05:02] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 10:05:02] [INFO   ] After capture - about 486112952 bytes (463.6 MiB) free. 
[2021-03-22 10:05:49] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 10:05:49] [INFO   ] After capture - about 410080144 bytes (391.1 MiB) free. 
[2021-03-22 10:53:40] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 10:53:40] [INFO   ] After capture - about 368867480 bytes (351.8 MiB) free. 
[2021-03-22 11:07:11] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:07:12] [INFO   ] After capture - about 346061944 bytes (330.0 MiB) free. 
[2021-03-22 11:09:36] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:09:37] [INFO   ] After capture - about 261577896 bytes (249.5 MiB) free. 
[2021-03-22 11:17:26] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:17:26] [INFO   ] After capture - about 264663600 bytes (252.4 MiB) free. 
[2021-03-22 11:20:48] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:20:48] [INFO   ] After capture - about 205830232 bytes (196.3 MiB) free. 
[2021-03-22 11:22:51] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:22:51] [INFO   ] After capture - about 160474312 bytes (153.0 MiB) free. 
[2021-03-22 11:23:42] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:23:42] [INFO   ] After capture - about 124909808 bytes (119.1 MiB) free. 
[2021-03-22 11:24:10] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:24:11] [INFO   ] After capture - about 161844304 bytes (154.3 MiB) free. 
[2021-03-22 11:26:53] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:26:53] [INFO   ] After capture - about 60763960 bytes (57.9 MiB) free. 
[2021-03-22 11:27:30] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:27:30] [INFO   ] After capture - about 104783032 bytes (99.9 MiB) free. 
[2021-03-22 11:28:09] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:28:10] [INFO   ] After capture - about 74047424 bytes (70.6 MiB) free. 
[2021-03-22 11:36:16] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:36:16] [INFO   ] After capture - about 31513456 bytes (30.1 MiB) free. 
[2021-03-22 11:50:01] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080] 
[2021-03-22 11:50:01] [INFO   ] After capture - about 27379448 bytes (26.1 MiB) free. 
[2021-03-22 12:16:51] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=5760,height=1080]

**Comment by gfmoore** [comment]
So I tried again and this time got the log. I didn't have word opened and I had to do about 8 or 9 grabs this time.
It does say out of memory error (I have 32GB RAM and hardly anything running.

@Creamers158 - that rectangle width looks large, but you did say you had 2? screens?

Gordon

```
[2021-03-22 08:56:58] [INFO   ] Ffmpeg found, specified in prefs file 
[2021-03-22 08:56:58] [INFO   ] Starting Windows global hotkey provider 
[2021-03-22 08:56:58] [INFO   ] Widget location = (765, 0). 
[2021-03-22 08:56:58] [INFO   ] Registering hotkey: HotKey{ctrl alt C} 
[2021-03-22 08:56:58] [INFO   ] Widget location = (765, 0). 
[2021-03-22 08:57:07] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 08:57:07] [INFO   ] After capture - about 90827064 bytes (86.6 MiB) free. 
[2021-03-22 08:57:20] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 08:57:20] [INFO   ] After capture - about 48107568 bytes (45.9 MiB) free. 
[2021-03-22 08:57:38] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 08:57:38] [INFO   ] After capture - about 30921152 bytes (29.5 MiB) free. 
[2021-03-22 08:58:28] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 08:58:28] [INFO   ] After capture - about 13431592 bytes (12.8 MiB) free. 
[2021-03-22 08:58:39] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at java.desktop/java.awt.Robot.createCompatibleImage(Robot.java:540)
	at java.desktop/java.awt.Robot.createScreenCapture(Robot.java:400)
	at info.ginj.ui.CaptureSelectionFrame$CaptureMainPane.<init>(CaptureSelectionFrame.java:157)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:138)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:56)
	at info.ginj.ui.AbstractAllDisplaysFrame.open(AbstractAllDisplaysFrame.java:62)
	at info.ginj.ui.CaptureSelectionFrame.open(CaptureSelectionFrame.java:98)
	at info.ginj.ui.StarWindow.onCapture(StarWindow.java:907)
	at info.ginj.ui.StarWindow$3.mouseClicked(StarWindow.java:541)
	at info.ginj.ui.listener.DragInsensitiveMouseClickListener.mouseReleased(DragInsensitiveMouseClickListener.java:61)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Window.processEvent(Window.java:2041)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
[2021-03-22 09:00:44] [INFO   ] StarWindow disposed. 
[2021-03-22 09:00:58] [INFO   ] Ffmpeg found, specified in prefs file 
[2021-03-22 09:00:58] [INFO   ] Starting Windows global hotkey provider 
[2021-03-22 09:00:58] [INFO   ] Widget location = (765, 0). 
[2021-03-22 09:00:58] [INFO   ] Registering hotkey: HotKey{ctrl alt C} 
[2021-03-22 09:00:58] [INFO   ] Widget location = (765, 0). 
[2021-03-22 09:01:20] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 09:01:21] [INFO   ] After capture - about 90762936 bytes (86.6 MiB) free. 
[2021-03-22 09:01:34] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 09:01:34] [INFO   ] After capture - about 48260560 bytes (46.0 MiB) free. 
[2021-03-22 09:01:51] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 09:01:51] [INFO   ] After capture - about 30454728 bytes (29.0 MiB) free. 
[2021-03-22 09:02:09] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
[2021-03-22 09:02:09] [INFO   ] After capture - about 13333288 bytes (12.7 MiB) free. 
[2021-03-22 09:02:21] [INFO   ] Capturing area: java.awt.Rectangle[x=-1920,y=0,width=3840,height=1080] 
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at java.desktop/java.awt.Robot.createCompatibleImage(Robot.java:540)
	at java.desktop/java.awt.Robot.createScreenCapture(Robot.java:400)
	at info.ginj.ui.CaptureSelectionFrame$CaptureMainPane.<init>(CaptureSelectionFrame.java:157)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:138)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:56)
	at info.ginj.ui.AbstractAllDisplaysFrame.open(AbstractAllDisplaysFrame.java:62)
	at info.ginj.ui.CaptureSelectionFrame.open(CaptureSelectionFrame.java:98)
	at info.ginj.ui.StarWindow.onCapture(StarWindow.java:907)
	at info.ginj.ui.StarWindow$3.mouseClicked(StarWindow.java:541)
	at info.ginj.ui.listener.DragInsensitiveMouseClickListener.mouseReleased(DragInsensitiveMouseClickListener.java:61)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Window.processEvent(Window.java:2041)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
[2021-03-22 15:27:57] [INFO   ] StarWindow disposed. 
[2021-03-22 15:30:23] [INFO   ] Ffmpeg found, specified in prefs file 
[2021-03-22 15:30:24] [INFO   ] Starting Windows global hotkey provider 
[2021-03-22 15:30:24] [INFO   ] Widget location = (765, 0). 
[2021-03-22 15:30:24] [INFO   ] Registering hotkey: HotKey{ctrl alt C} 
[2021-03-22 15:30:24] [INFO   ] Widget location = (765, 0). 
[2021-03-22 15:30:27] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:30:28] [INFO   ] After capture - about 109812784 bytes (104.7 MiB) free. 
[2021-03-22 15:30:35] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:30:36] [INFO   ] After capture - about 86775744 bytes (82.8 MiB) free. 
[2021-03-22 15:30:43] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:30:43] [INFO   ] After capture - about 76928528 bytes (73.4 MiB) free. 
[2021-03-22 15:30:49] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:30:49] [INFO   ] After capture - about 65033832 bytes (62.0 MiB) free. 
[2021-03-22 15:30:55] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:30:55] [INFO   ] After capture - about 57568528 bytes (54.9 MiB) free. 
[2021-03-22 15:31:02] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:31:02] [INFO   ] After capture - about 47662184 bytes (45.5 MiB) free. 
[2021-03-22 15:31:08] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:31:08] [INFO   ] After capture - about 38451144 bytes (36.7 MiB) free. 
[2021-03-22 15:31:13] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:31:13] [INFO   ] After capture - about 29200360 bytes (27.8 MiB) free. 
[2021-03-22 15:31:19] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:31:19] [INFO   ] After capture - about 20128704 bytes (19.2 MiB) free. 
[2021-03-22 15:31:25] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
[2021-03-22 15:31:25] [INFO   ] After capture - about 10202856 bytes (9.7 MiB) free. 
[2021-03-22 15:31:31] [INFO   ] Capturing area: java.awt.Rectangle[x=0,y=0,width=1920,height=1080] 
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at java.desktop/java.awt.Robot.createCompatibleImage(Robot.java:540)
	at java.desktop/java.awt.Robot.createScreenCapture(Robot.java:400)
	at info.ginj.ui.CaptureSelectionFrame$CaptureMainPane.<init>(CaptureSelectionFrame.java:157)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:138)
	at info.ginj.ui.CaptureSelectionFrame.createContentPane(CaptureSelectionFrame.java:56)
	at info.ginj.ui.AbstractAllDisplaysFrame.open(AbstractAllDisplaysFrame.java:62)
	at info.ginj.ui.CaptureSelectionFrame.open(CaptureSelectionFrame.java:98)
	at info.ginj.ui.StarWindow.onCapture(StarWindow.java:907)
	at info.ginj.ui.StarWindow$3.mouseClicked(StarWindow.java:541)
	at info.ginj.ui.listener.DragInsensitiveMouseClickListener.mouseReleased(DragInsensitiveMouseClickListener.java:61)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Window.processEvent(Window.java:2041)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.executePrivileged(AccessController.java:753)
```

**Comment by gfmoore** [comment]
Does this thread help?
[https://stackoverflow.com/questions/3841723/exception-in-thread-awt-eventqueue-0-java-lang-outofmemoryerror-java-heap-spa]

**Comment by vicnevicne** [comment]
Hi,
OK, the good news is that your logs both confirm the root cause : the lines starting with "After capture" indicate a decreasing free memory after each capture, to the point where there is no memory left and then problems start. Disappearing sun, cross lines appearing or not, or any other weird symptoms.

Although the linked page has the exact same message `Exception in thread '"WT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space`, all it means is that we run out of memory when we start a new capture and there isn't enough ram available, but it doesn't tell anything about why Java what is using all that memory.

I'm going to add some logging and try to reproduce the issue here...

Vicne

**Comment by gfmoore** [comment]
Sorry missed the question. I personally copy to clipboard mostly.

**Comment by gfmoore** [comment]
I assume you are struggling to find a fix for this problem?
Perhaps you could add a workaround. How about a restart on the  Ginj notification icon which is still visible. At least it would save a few mouse/button operations. :)

**Comment by vicnevicne** [comment]
Version 0.4.5 was released with a massive refactoring and a new attempt at fixing this memory leak, clearly caused by some windows that kept references to the previous captures but were not freed by the VM.
In the new version, the windows are still not freed (can't find a way - see https://stackoverflow.com/questions/39437481/jframe-is-never-garbage-collected ), but the references they held to the previous captures are removed by code so the associated memory should be recycled by the garbage collector, reducing memory leak (and crash rate) by a large factor (10000 or so).
All feedback is welcome !

**Comment by gfmoore** [comment]
Just thought I'd post that since the latest refactoring update I don't seem to have come across this issue anymore. I hope I haven't jinxed it by saying that :)  . But if solved, well done. 👍🏻

**Comment by Creamers158** [comment]
Same here, problem seems solved. Great job! 👍

**Comment by vicnevicne** [comment]
Excellent. Thanks for the feedback.
I'm closing that issue that haunted us for 10 months, hopefully for good :-)
